### ISSUE TITLE
[Feature Request]: Allow top and bottom locations

### ISSUE THREAD

**Issue by linspw** [webdevnerdstuff/vuetify-resize-drawer#31]
### Is your feature request related to a problem? Please describe.

Your project is incredible, congratulations!

A feature suggestion that I imagine many would use is to use the drawer vertically, to allow similar use to the modal on mobile

### Describe the solution you'd like

Example:
https://ionicframework.com/docs/api/modal#interacting-with-background-content

### Describe alternatives you've considered

None

### Additional context

[screen-capture (7).webm](https://github.com/webdevnerdstuff/vuetify-resize-drawer/assets/43552865/d6c97ac2-facd-4b15-abc2-b377d7e48055)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
It is something that I have explored years ago when I only had a Vuetify 2 version, so I'm not opposed to looking into it again. I'll see about revisiting the idea when I have some more free time.

**Comment by linspw** [comment]
Thank you very much for your response and attention

If you see that it makes sense and need help thinking about implementation, you can contact me.

**Comment by webdevnerdstuff** [comment]
@linspw Finally had some free time to work on adding this. If you want to give a test run it would be appreciated. It's currently on brach `issue-31`.

[Playground instructions](https://webdevnerdstuff.github.io/vuetify-resize-drawer/#playground)
