### ISSUE TITLE
[Feature Request]: Allow programmatically changing the width

### ISSUE THREAD

**Issue by DEFENDORe** [webdevnerdstuff/vuetify-resize-drawer#37]
### Is your feature request related to a problem? Please describe.

I can't seem to figure out a way to manually set/update the width after the component has been mounted. 

### Describe the solution you'd like

Add an exposed method to set the width manually.

### Describe alternatives you've considered

Or maybe 'watch' the width property and update the layout accordingly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
You can already set the width manually with the `width` prop. If you save the width to local/session storage it will use that width when mounted. If you don't want it to save to the storage and have it set to the width each time the page is loaded you would have to set `save-width` to `false`. The `width` also acts as the "default" the drawer will resize to when double clicking on the handle.

**Comment by DEFENDORe** [comment]
I'm running into a scenario where I would like the drawer to be the full device width when a user is on the 'xs' breakpoint. I tried: `<VResizeDrawer :width="xs ? '100%' : '300px'" :touchless="xs" :save-width="false" permanent...` to no avail and discovered it uses the width property on initialization only.

When a user resizes their browser or rotates their device to the 'xs' breakpoint, and the drawer is smaller than the new viewport, the drawer will remain small. It'd be cool if I could update it manually even if it was an exposed method.

**Comment by webdevnerdstuff** [comment]
You can just add `style="width: 100%"` depending on the breakpoint on the component.

**Comment by DEFENDORe** [comment]
Posting this in case it helps somebody in the future..

After playing around a bit I found that I needed to apply two separate classes to get the job done, otherwise the drawer would remain partially visible when closed.

`v-model="drawerState" :class="{ 'mobileResizeDrawer': xs, 'mobileResizeDrawerClosed' : xs && !drawerState}" ...` 

`.mobileResizeDrawer {
  width: 100% !important;
}`
`.mobileResizeDrawerClosed {
  transform: translateX(-100%) !important;
}`
